import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import useStore from '../store/app';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const stepName = useStore((state) => state.stepName);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{stepName}</div>
    </div>
  );
};

export default Home;
