import type { NextPage } from 'next'
import Head from 'next/head'
import { Stack, Button, AppShell } from '@mantine/core';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell padding="md" header={<Header />} footer={<Footer />}>
        <main>
          <Stack>
            <span className='text-3xl font-bold underline'>content</span>
            <Button>something</Button>
          </Stack>
        </main>
      </AppShell>
    </>
  )
}

export default Home
